import { file } from "bun";

// This script is run from the `md2html/` package root.
const themesCssPath = "./node_modules/daisyui/themes.css";
const classlessCssPath = "./src/infrastructure/classless.css";
const outPath = "./src/infrastructure/template.generated.html";
const outTsPath = "./src/infrastructure/template.generated.ts";

const TEMPLATE = `<!DOCTYPE html>
<html lang="en" data-theme="__THEME__">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Converted Document</title>
    <style>
__CSS__
    </style>
  </head>
  <body>
    <main>
      <article>
__CONTENT__
      </article>
    </main>
  </body>
</html>
`;

try {
  const themesCss = await file(themesCssPath).text();
  const classlessCss = await file(classlessCssPath).text();
  const css = `${themesCss}\n\n${classlessCss}`;
  const html = TEMPLATE.replace("__CSS__", css);
  await file(outPath).write(html);
  const escapedForTemplateLiteral = html.replaceAll("`", "\\`").replaceAll("${", "\\${");
  await file(outTsPath).write(
    [
      "// This file is generated by `bun run generate:template`.",
      "// Do not edit manually.",
      "",
      `export const TEMPLATE_HTML = \`${escapedForTemplateLiteral}\` as const;`,
      "",
    ].join("\n")
  );
  console.log(`Generated ${outPath}`);
  console.log(`Generated ${outTsPath}`);
} catch (e) {
  console.error("Failed to generate template:", e);
  process.exit(1);
}
